### (1) Importing Libraries

In [1]:
import numpy   as np
import pandas  as pd
import scipy   as sp
import sklearn as sk

# from sklearn.impute          import SimpleImputer
# from sklearn.preprocessing   import StandardScaler
# from sklearn.preprocessing   import LabelEncoder
# from sklearn.model_selection import train_test_split

print (np.__version__)
print (pd.__version__)
print (sp.__version__)
print (sk.__version__)

1.19.0
0.25.3
1.4.1
0.22.2.post1


### (2) Importing Data

In [2]:
# reading data from file
dataSet = pd.read_csv('../Data/zillow.csv')
print (dataSet)

    Index   "sq ft"   "Beds"   "Baths"   "Zip"   "Year"   "List Price ($)"
0       1      2222        3       3.5   32312     1981             250000
1       2      1628        3       2.0   32308     2009             185000
2       3      3824        5       4.0   32312     1954             399000
3       4      1137        3       2.0   32309     1993             150000
4       5      3560        6       4.0   32309     1973             315000
5       6      2893        4       3.0   32312     1994             699000
6       7      3631        4       3.0   32309     1996             649000
7       8      2483        4       3.0   32312     2016             399000
8       9      2400        4       4.0   32312     2002             613000
9      10      1997        3       3.0   32311     2006             295000
10     11      2097        4       3.0   32311     2016             290000
11     12      3200        5       4.0   32312     1964             465000
12     13      4892      

In [3]:
# splitting into X (inputs) and Y (targets)
X = dataSet.iloc[:, :-1].values
Y = dataSet.iloc[:,  -1].values
print(X)
print(Y)

[[1.0000e+00 2.2220e+03 3.0000e+00 3.5000e+00 3.2312e+04 1.9810e+03]
 [2.0000e+00 1.6280e+03 3.0000e+00 2.0000e+00 3.2308e+04 2.0090e+03]
 [3.0000e+00 3.8240e+03 5.0000e+00 4.0000e+00 3.2312e+04 1.9540e+03]
 [4.0000e+00 1.1370e+03 3.0000e+00 2.0000e+00 3.2309e+04 1.9930e+03]
 [5.0000e+00 3.5600e+03 6.0000e+00 4.0000e+00 3.2309e+04 1.9730e+03]
 [6.0000e+00 2.8930e+03 4.0000e+00 3.0000e+00 3.2312e+04 1.9940e+03]
 [7.0000e+00 3.6310e+03 4.0000e+00 3.0000e+00 3.2309e+04 1.9960e+03]
 [8.0000e+00 2.4830e+03 4.0000e+00 3.0000e+00 3.2312e+04 2.0160e+03]
 [9.0000e+00 2.4000e+03 4.0000e+00 4.0000e+00 3.2312e+04 2.0020e+03]
 [1.0000e+01 1.9970e+03 3.0000e+00 3.0000e+00 3.2311e+04 2.0060e+03]
 [1.1000e+01 2.0970e+03 4.0000e+00 3.0000e+00 3.2311e+04 2.0160e+03]
 [1.2000e+01 3.2000e+03 5.0000e+00 4.0000e+00 3.2312e+04 1.9640e+03]
 [1.3000e+01 4.8920e+03 5.0000e+00 6.0000e+00 3.2311e+04 2.0050e+03]
 [1.4000e+01 1.1280e+03 2.0000e+00 1.0000e+00 3.2303e+04 1.9550e+03]
 [1.5000e+01 1.3810e+03 3.0000e+00

### (3) Feature Scaling

In [4]:
from sklearn.preprocessing import StandardScaler

scalar = StandardScaler()

X = scalar.fit_transform(X)
print ("X = ")
print (X)
print ("=============================================")

X = 
[[-1.64750894 -0.39108016 -0.88259602  0.28161231  0.89526602 -0.6450088 ]
 [-1.47408695 -0.93941397 -0.88259602 -1.0181368  -0.25991594  0.90522695]
 [-1.30066495  1.0877595   1.1941005   0.71486201  0.89526602 -2.13987899]
 [-1.12724296 -1.39266633 -0.88259602 -1.0181368   0.02887955  0.01937795]
 [-0.95382097  0.84405558  2.23244877  0.71486201  0.02887955 -1.0879333 ]
 [-0.78039897  0.22833395  0.15575224 -0.1516374   0.89526602  0.07474351]
 [-0.60697698  0.90959717  0.15575224 -0.1516374   0.02887955  0.18547463]
 [-0.43355498 -0.15014561  0.15575224 -0.1516374   0.89526602  1.29278588]
 [-0.26013299 -0.22676465  0.15575224  0.71486201  0.89526602  0.51766801]
 [-0.086711   -0.59878236 -0.88259602 -0.1516374   0.60647053  0.73913026]
 [ 0.086711   -0.50647027  0.15575224 -0.1516374   0.60647053  1.29278588]
 [ 0.26013299  0.51173206  1.1941005   0.71486201  0.89526602 -1.58622336]
 [ 0.43355498  2.0736526   1.1941005   2.44786081  0.60647053  0.6837647 ]
 [ 0.60697698 -1.400

### (4) Splitting data into trainig and testing datasets

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split( X , Y , test_size = 0.2, random_state = 0)

print ("X_train = ")
print (X_train)
print ("Y_train = ")
print (Y_train)
print ("---------------------------------------------")
print ("X_test = ")
print (X_test)
print ("Y_test = ")
print (Y_test)
print ("=============================================")

X_train = 
[[ 0.086711   -0.50647027  0.15575224 -0.1516374   0.60647053  1.29278588]
 [ 1.30066495 -1.37328079 -0.88259602 -1.0181368  -1.7038934   0.01937795]
 [-0.60697698  0.90959717  0.15575224 -0.1516374   0.02887955  0.18547463]
 [ 0.60697698 -1.40097441 -1.92094429 -1.8846362  -1.7038934  -2.08451343]
 [-0.95382097  0.84405558  2.23244877  0.71486201  0.02887955 -1.0879333 ]
 [-1.30066495  1.0877595   1.1941005   0.71486201  0.89526602 -2.13987899]
 [-0.78039897  0.22833395  0.15575224 -0.1516374   0.89526602  0.07474351]
 [ 0.78039897 -1.16742483 -0.88259602 -1.0181368  -2.28148438  0.73913026]
 [-0.086711   -0.59878236 -0.88259602 -0.1516374   0.60647053  0.73913026]
 [-0.43355498 -0.15014561  0.15575224 -0.1516374   0.89526602  1.29278588]
 [ 1.12724296 -0.10398957 -0.88259602 -1.0181368   0.31767504 -0.09135318]
 [ 0.26013299  0.51173206  1.1941005   0.71486201  0.89526602 -1.58622336]
 [-1.12724296 -1.39266633 -0.88259602 -1.0181368   0.02887955  0.01937795]
 [-1.64750894 