### (1) Importing Libraries

In [1]:
import numpy   as np
import pandas  as pd
import scipy   as sp
import sklearn as sk

# from sklearn.impute          import SimpleImputer
# from sklearn.preprocessing   import StandardScaler
# from sklearn.preprocessing   import LabelEncoder
# from sklearn.model_selection import train_test_split

print (np.__version__)
print (pd.__version__)
print (sp.__version__)
print (sk.__version__)

1.19.0
0.25.3
1.4.1
0.22.2.post1


### (2) Importing Data
#### (2-1) CSV data

In [2]:
# reading data from file
dataSet = pd.read_csv('../Data/zillow.csv')
print (dataSet)

    Index   "sq ft"   "Beds"   "Baths"   "Zip"   "Year"   "List Price ($)"
0       1      2222        3       3.5   32312     1981             250000
1       2      1628        3       2.0   32308     2009             185000
2       3      3824        5       4.0   32312     1954             399000
3       4      1137        3       2.0   32309     1993             150000
4       5      3560        6       4.0   32309     1973             315000
5       6      2893        4       3.0   32312     1994             699000
6       7      3631        4       3.0   32309     1996             649000
7       8      2483        4       3.0   32312     2016             399000
8       9      2400        4       4.0   32312     2002             613000
9      10      1997        3       3.0   32311     2006             295000
10     11      2097        4       3.0   32311     2016             290000
11     12      3200        5       4.0   32312     1964             465000
12     13      4892      

In [3]:
# splitting into X (inputs) and Y (targets)
X = dataSet.iloc[:, :-1].values
Y = dataSet.iloc[:,  -1].values
print(X)
print(Y)

[[1.0000e+00 2.2220e+03 3.0000e+00 3.5000e+00 3.2312e+04 1.9810e+03]
 [2.0000e+00 1.6280e+03 3.0000e+00 2.0000e+00 3.2308e+04 2.0090e+03]
 [3.0000e+00 3.8240e+03 5.0000e+00 4.0000e+00 3.2312e+04 1.9540e+03]
 [4.0000e+00 1.1370e+03 3.0000e+00 2.0000e+00 3.2309e+04 1.9930e+03]
 [5.0000e+00 3.5600e+03 6.0000e+00 4.0000e+00 3.2309e+04 1.9730e+03]
 [6.0000e+00 2.8930e+03 4.0000e+00 3.0000e+00 3.2312e+04 1.9940e+03]
 [7.0000e+00 3.6310e+03 4.0000e+00 3.0000e+00 3.2309e+04 1.9960e+03]
 [8.0000e+00 2.4830e+03 4.0000e+00 3.0000e+00 3.2312e+04 2.0160e+03]
 [9.0000e+00 2.4000e+03 4.0000e+00 4.0000e+00 3.2312e+04 2.0020e+03]
 [1.0000e+01 1.9970e+03 3.0000e+00 3.0000e+00 3.2311e+04 2.0060e+03]
 [1.1000e+01 2.0970e+03 4.0000e+00 3.0000e+00 3.2311e+04 2.0160e+03]
 [1.2000e+01 3.2000e+03 5.0000e+00 4.0000e+00 3.2312e+04 1.9640e+03]
 [1.3000e+01 4.8920e+03 5.0000e+00 6.0000e+00 3.2311e+04 2.0050e+03]
 [1.4000e+01 1.1280e+03 2.0000e+00 1.0000e+00 3.2303e+04 1.9550e+03]
 [1.5000e+01 1.3810e+03 3.0000e+00

-----------
#### (2-2) MATLAB mat-file

In [13]:
from scipy.io import loadmat
data = loadmat('../Data/zillow.mat')
X = data['X']; X = X[:, 1:]  # the first column is just index
Y = data['Y'];

print (X)
print (Y)

[[1.0000e+00 2.2220e+03 3.0000e+00 3.5000e+00 3.2312e+04 1.9810e+03]
 [2.0000e+00 1.6280e+03 3.0000e+00 2.0000e+00 3.2308e+04 2.0090e+03]
 [3.0000e+00 3.8240e+03 5.0000e+00 4.0000e+00 3.2312e+04 1.9540e+03]
 [4.0000e+00 1.1370e+03 3.0000e+00 2.0000e+00 3.2309e+04 1.9930e+03]
 [5.0000e+00 3.5600e+03 6.0000e+00 4.0000e+00 3.2309e+04 1.9730e+03]
 [6.0000e+00 2.8930e+03 4.0000e+00 3.0000e+00 3.2312e+04 1.9940e+03]
 [7.0000e+00 3.6310e+03 4.0000e+00 3.0000e+00 3.2309e+04 1.9960e+03]
 [8.0000e+00 2.4830e+03 4.0000e+00 3.0000e+00 3.2312e+04 2.0160e+03]
 [9.0000e+00 2.4000e+03 4.0000e+00 4.0000e+00 3.2312e+04 2.0020e+03]
 [1.0000e+01 1.9970e+03 3.0000e+00 3.0000e+00 3.2311e+04 2.0060e+03]
 [1.1000e+01 2.0970e+03 4.0000e+00 3.0000e+00 3.2311e+04 2.0160e+03]
 [1.2000e+01 3.2000e+03 5.0000e+00 4.0000e+00 3.2312e+04 1.9640e+03]
 [1.3000e+01 4.8920e+03 5.0000e+00 6.0000e+00 3.2311e+04 2.0050e+03]
 [1.4000e+01 1.1280e+03 2.0000e+00 1.0000e+00 3.2303e+04 1.9550e+03]
 [1.5000e+01 1.3810e+03 3.0000e+00

-----------
#### (2-3) MS Excel file

In [35]:
data = pd.read_excel('../Data/zillow.xlsx')

# for this one you need the optional dependency 'xlrd'. (xlrd >= 1.0.0)
# $ pip3 install xlrd


print (data.describe())
print ('-----------------------')
print (data.size)
print (data.shape)
print ('-----------------------')
X = data.iloc[:, :-1].values
Y = data.iloc[:,  -1].values

print (X)
print (Y)

        0.0        1.0          2222.0     3.0        3.5           32312.0   \
count  19.000000  19.000000    19.000000  19.000000  19.000000     19.000000   
mean   10.000000  11.000000  2667.947368   3.894737   3.157895  32308.736842   
std     5.627314   5.627314  1137.274054   0.994135   1.213954      3.572147   
min     1.000000   2.000000  1128.000000   2.000000   1.000000  32301.000000   
25%     5.500000   6.500000  1812.500000   3.000000   2.000000  32308.500000   
50%    10.000000  11.000000  2497.000000   4.000000   3.000000  32309.000000   
75%    14.500000  15.500000  3595.500000   4.500000   4.000000  32311.500000   
max    19.000000  20.000000  4892.000000   6.000000   6.000000  32312.000000   

          1981.0         250000.0  
count    19.000000      19.000000  
mean   1993.263158  390463.157895  
std      18.829180  208917.440394  
min    1954.000000   89000.000000  
25%    1990.500000  237000.000000  
50%    1996.000000  365000.000000  
75%    2006.000000  559450.