# General Form

## (A) All Numerical Values

### (1) Importing Libraries

In [1]:
import numpy   as np
import pandas  as pd
import scipy   as sp
import sklearn as sk

# from sklearn.impute          import SimpleImputer
# from sklearn.preprocessing   import StandardScaler
# from sklearn.preprocessing   import LabelEncoder
# from sklearn.model_selection import train_test_split

print (np.__version__)
print (pd.__version__)
print (sp.__version__)
print (sk.__version__)

1.19.0
0.25.3
1.4.1
0.22.2.post1


### (2) Importing Data
The dataset includes missing data


In [2]:
dataSet = pd.read_csv('../Data/zillow_incomplete.csv')
print (dataSet)

X = dataSet.iloc[:, :-1].values
Y = dataSet.iloc[:,  -1].values
print(X)
print(Y)

    Index   "sq ft"   "Beds"   "Baths"   "Zip"   "Year"   "List Price ($)"
0       1    2222.0      3.0       3.5   32312     1981             250000
1       2    1628.0      3.0       2.0   32308     2009             185000
2       3    3824.0      5.0       4.0   32312     1954             399000
3       4    1137.0      3.0       2.0   32309     1993             150000
4       5    3560.0      6.0       4.0   32309     1973             315000
5       6    2893.0      4.0       NaN   32312     1994             699000
6       7    3631.0      4.0       3.0   32309     1996             649000
7       8    2483.0      4.0       3.0   32312     2016             399000
8       9       NaN      4.0       4.0   32312     2002             613000
9      10    1997.0      3.0       3.0   32311     2006             295000
10     11    2097.0      4.0       3.0   32311     2016             290000
11     12    3200.0      5.0       4.0   32312     1964             465000
12     13    4892.0      

### (3) Handling Missing Data

Imputer Documentation: https://scikit-learn.org/stable/modules/generated/sklearn.impute.SimpleImputer.html

In [3]:
from sklearn.impute import SimpleImputer

#imputer= SimpleImputer(missing_values = "NaN" , strategy = "mean") 
imputer = SimpleImputer(missing_values = np.nan, strategy = "mean")
print(imputer)

imputer=imputer.fit(X)
print(imputer)

X=imputer.transform(X)
print(X)

SimpleImputer(add_indicator=False, copy=True, fill_value=None,
              missing_values=nan, strategy='mean', verbose=0)
SimpleImputer(add_indicator=False, copy=True, fill_value=None,
              missing_values=nan, strategy='mean', verbose=0)
[[1.00000000e+00 2.22200000e+03 3.00000000e+00 3.50000000e+00
  3.23120000e+04 1.98100000e+03]
 [2.00000000e+00 1.62800000e+03 3.00000000e+00 2.00000000e+00
  3.23080000e+04 2.00900000e+03]
 [3.00000000e+00 3.82400000e+03 5.00000000e+00 4.00000000e+00
  3.23120000e+04 1.95400000e+03]
 [4.00000000e+00 1.13700000e+03 3.00000000e+00 2.00000000e+00
  3.23090000e+04 1.99300000e+03]
 [5.00000000e+00 3.56000000e+03 6.00000000e+00 4.00000000e+00
  3.23090000e+04 1.97300000e+03]
 [6.00000000e+00 2.89300000e+03 4.00000000e+00 3.18421053e+00
  3.23120000e+04 1.99400000e+03]
 [7.00000000e+00 3.63100000e+03 4.00000000e+00 3.00000000e+00
  3.23090000e+04 1.99600000e+03]
 [8.00000000e+00 2.48300000e+03 4.00000000e+00 3.00000000e+00
  3.23120000e+04 2.0160

### (4) Feature Scaling

In [4]:
from sklearn.preprocessing import StandardScaler

scalar = StandardScaler()

X = scalar.fit_transform(X)
print ("X = ")
print (X)
print ("=============================================")

X = 
[[-1.64750894e+00 -4.87453380e-01 -9.48699712e-01  2.73797115e-01
   8.95266022e-01 -6.45008802e-01]
 [-1.47408695e+00 -1.05792750e+00 -9.48699712e-01 -1.02673918e+00
  -2.59915942e-01  9.05226946e-01]
 [-1.30066495e+00  1.05109803e+00  1.17192317e+00  7.07309214e-01
   8.95266022e-01 -2.13987899e+00]
 [-1.12724296e+00 -1.52948102e+00 -9.48699712e-01 -1.02673918e+00
   2.88795491e-02  1.93779468e-02]
 [-9.53820966e-01  7.97553975e-01  2.23223462e+00  7.07309214e-01
   2.88795491e-02 -1.08793330e+00]
 [-7.80398973e-01  1.56971086e-01  1.11611731e-01  0.00000000e+00
   8.95266022e-01  7.47435093e-02]
 [-6.06976979e-01  8.65741959e-01  1.11611731e-01 -1.59714984e-01
   2.88795491e-02  1.85474634e-01]
 [-4.33554985e-01 -2.36790510e-01  1.11611731e-01 -1.59714984e-01
   8.95266022e-01  1.29278588e+00]
 [-2.60132991e-01  0.00000000e+00  1.11611731e-01  7.07309214e-01
   8.95266022e-01  5.17668009e-01]
 [-8.67109970e-02 -7.03542061e-01 -9.48699712e-01 -1.59714984e-01
   6.06470531e-01  7

### (5) Splitting data into trainig and testing datasets

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split( X , Y , test_size = 0.2, random_state = 0)

print ("X_train = ")
print (X_train)
print ("Y_train = ")
print (Y_train)
print ("---------------------------------------------")
print ("X_test = ")
print (X_test)
print ("Y_test = ")
print (Y_test)
print ("=============================================")


X_train = 
[[ 8.67109970e-02 -6.07502647e-01  1.11611731e-01 -1.59714984e-01
   6.06470531e-01  1.29278588e+00]
 [ 1.30066495e+00 -1.50931274e+00  4.70872871e-16 -1.02673918e+00
  -1.70389340e+00  1.93779468e-02]
 [-6.06976979e-01  8.65741959e-01  1.11611731e-01 -1.59714984e-01
   2.88795491e-02  1.85474634e-01]
 [ 6.06976979e-01 -1.53812457e+00 -2.00901115e+00 -1.89376338e+00
  -1.70389340e+00 -2.08451343e+00]
 [-9.53820966e-01  7.97553975e-01  2.23223462e+00  7.07309214e-01
   2.88795491e-02 -1.08793330e+00]
 [-1.30066495e+00  1.05109803e+00  1.17192317e+00  7.07309214e-01
   8.95266022e-01 -2.13987899e+00]
 [-7.80398973e-01  1.56971086e-01  1.11611731e-01  0.00000000e+00
   8.95266022e-01  7.47435093e-02]
 [ 7.80398973e-01  0.00000000e+00 -9.48699712e-01 -1.02673918e+00
  -2.28148438e+00  7.39130258e-01]
 [-8.67109970e-02 -7.03542061e-01 -9.48699712e-01 -1.59714984e-01
   6.06470531e-01  7.39130258e-01]
 [-4.33554985e-01 -2.36790510e-01  1.11611731e-01 -1.59714984e-01
   8.95266022e

-----------

## (B) Includes Categorical Data

### (1) Importing Libraries

In [6]:
import numpy   as np
import pandas  as pd
import scipy   as sp
import sklearn as sk

# from sklearn.impute          import SimpleImputer
# from sklearn.preprocessing   import StandardScaler
# from sklearn.preprocessing   import LabelEncoder
# from sklearn.model_selection import train_test_split

print (np.__version__)
print (pd.__version__)
print (sp.__version__)
print (sk.__version__)

1.19.0
0.25.3
1.4.1
0.22.2.post1


### (2) Importing Data
The dataset includes missing data


In [7]:
dataSet = pd.read_csv('../Data/dataset1.csv')
print (dataSet)

X = dataSet.iloc[:, :-1].values
Y = dataSet.iloc[:,  -1].values
print(X)
print(Y)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes
[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [8]:
print (X[:, 1:3])
print (X[:, -1])
print (X[:, -2:])
# imputer = imputer.fit(X[:, 1:3])


print(   type(X)                           )
print(   pd.isnull(X[:, 1:3])              )
print(   np.any(pd.isnull(X[:, 1:3]))      )
print(   np.all(pd.isnull(X[:, 1:3]))      )


[[44.0 72000.0]
 [27.0 48000.0]
 [30.0 54000.0]
 [38.0 61000.0]
 [40.0 nan]
 [35.0 58000.0]
 [nan 52000.0]
 [48.0 79000.0]
 [50.0 83000.0]
 [37.0 67000.0]]
[72000.0 48000.0 54000.0 61000.0 nan 58000.0 52000.0 79000.0 83000.0
 67000.0]
[[44.0 72000.0]
 [27.0 48000.0]
 [30.0 54000.0]
 [38.0 61000.0]
 [40.0 nan]
 [35.0 58000.0]
 [nan 52000.0]
 [48.0 79000.0]
 [50.0 83000.0]
 [37.0 67000.0]]
<class 'numpy.ndarray'>
[[False False]
 [False False]
 [False False]
 [False False]
 [False  True]
 [False False]
 [ True False]
 [False False]
 [False False]
 [False False]]
True
False


### (3) Handling Missing Data

In [9]:
# Handling missing data

from sklearn.impute import SimpleImputer

#imputer= SimpleImputer(missing_values = "NaN" , strategy = "mean") 
imputer = SimpleImputer(missing_values = np.nan, strategy = "mean")
print(imputer)

imputer=imputer.fit(X[:,1:3])
print(imputer)

X[:,1:3]=imputer.transform(X[:,1:3])
print(X)


SimpleImputer(add_indicator=False, copy=True, fill_value=None,
              missing_values=nan, strategy='mean', verbose=0)
SimpleImputer(add_indicator=False, copy=True, fill_value=None,
              missing_values=nan, strategy='mean', verbose=0)
[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


### (4) Encoding Categorical Data

In [10]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
X[ : , 0] = encoder.fit_transform(X[ : , 0])
print (X)


[[0 44.0 72000.0]
 [2 27.0 48000.0]
 [1 30.0 54000.0]
 [2 38.0 61000.0]
 [1 40.0 63777.77777777778]
 [0 35.0 58000.0]
 [2 38.77777777777778 52000.0]
 [0 48.0 79000.0]
 [1 50.0 83000.0]
 [0 37.0 67000.0]]


### (5) Splitting data into trainig and testing datasets

In [11]:

# Splitting the dataset into training and test sets
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split( X , Y , test_size = 0.2, random_state = 0)

print (X_train)
print (Y_train)

print (X_test)
print (Y_test)



[[1 40.0 63777.77777777778]
 [0 37.0 67000.0]
 [2 27.0 48000.0]
 [2 38.77777777777778 52000.0]
 [0 48.0 79000.0]
 [2 38.0 61000.0]
 [0 44.0 72000.0]
 [0 35.0 58000.0]]
['Yes' 'Yes' 'Yes' 'No' 'Yes' 'No' 'No' 'Yes']
[[1 30.0 54000.0]
 [1 50.0 83000.0]]
['No' 'No']


### (6) Feature Scaling

In [12]:
from sklearn.preprocessing import StandardScaler

scalar = StandardScaler()

X_train = scalar.fit_transform(X_train)
X_test  = scalar.fit_transform(X_test)

print (X_train)
print (X_test)

[[ 0.13483997  0.26306757  0.12381479]
 [-0.94387981 -0.25350148  0.46175632]
 [ 1.21355975 -1.97539832 -1.53093341]
 [ 1.21355975  0.05261351 -1.11141978]
 [-0.94387981  1.64058505  1.7202972 ]
 [ 1.21355975 -0.0813118  -0.16751412]
 [-0.94387981  0.95182631  0.98614835]
 [-0.94387981 -0.59788085 -0.48214934]]
[[ 0. -1. -1.]
 [ 0.  1.  1.]]
